/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutmeRouteImport } from './routes/aboutme'
import { Route as IndexRouteImport } from './routes/index'

const AboutmeRoute = AboutmeRouteImport.update({
  id: '/aboutme',
  path: '/aboutme',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aboutme': typeof AboutmeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aboutme': typeof AboutmeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aboutme': typeof AboutmeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aboutme'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aboutme'
  id: '__root__' | '/' | '/aboutme'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutmeRoute: typeof AboutmeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/aboutme': {
      id: '/aboutme'
      path: '/aboutme'
      fullPath: '/aboutme'
      preLoaderRoute: typeof AboutmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutmeRoute: AboutmeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
